name: Upload a new version to the PYPI

on:
  release:
    types: [created]

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Check code and run tests before publishing
        run: make check && make test
      - name: Build and publish package
        run: poetry version ${GITHUB_REF_NAME#v} && poetry publish --build
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
